language: go
go:
- tip
before_install:
  - go get golang.org/x/lint/golint
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || $HOME/gopath/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN'
  - $HOME/gopath/bin/golint ./...
  - go vet
  - go test -v ./...
notifications:
  email:
    on_success: never
    on_failure: change
env:
  global:
    secure: QdRpw4yyGY1BT+eF+t2HrhqVgFI0xFy+leaXtGvQ61L6HdfPYwOfxe5MvixisqFrjHdDEI1Do5XaMTIq55uLmzA51IoMInimEeNrXUIpyPEeolVHdCMEZAMw3n6F1FjUKm5YM2CTDpitvlNk/NoaHaOKrB5kQSs3MOcKNH/l9yg=
